### ISSUE TITLE
Support for Uni Trier Bibliothek

### ISSUE THREAD

**Issue by cmlnet** [raphaelm/opacclient#106]
Would love to see support for the university library in Trier.

See: http://tricat.uni-trier.de/

I'm more than happy to help you, if I can :)

**Comment by johan12345** [comment]
Uni Trier Bibliothek is now supported (since 6884ff0). However, account related functions (view lent and reserved items, make and cancel reservations, etc.) are not supported yet because we don't have an account for testing in any Primo library.

**Comment by cmlnet** [comment]
Thanks for the update, that's great news. :+1: 

I have an account for the library of the Karlsruhe Institute of Technology (KIT) which uses Primo as well. So I might be able to do some testing.

**Comment by raphaelm** [comment]
We'll get back to you when it comes to testing, but for *implementation*, this is probably not enough, because the person implementing it needs unlimited and direct access to a user account to have a chance implementing it in a good way.
