### ISSUE TITLE
gradle build

### ISSUE THREAD

**Issue by hurzl** [raphaelm/opacclient#279]
is gone?

**Comment by johan12345** [comment]
No, it's now merged into `master`.

**Comment by hurzl** [comment]
Achso, jetzt in opacclient!

**Comment by johan12345** [comment]
Genau. Das hat den Vorteil, dass man den Ordner, in den man das Repository klont, umbenennen kann, ohne, dass Android Studio dann verwirrt ist und neue `.iml`-Dateien erstellt.
