### ISSUE TITLE
Code style refurbishment

### ISSUE THREAD

**Issue by raphaelm** [raphaelm/opacclient#281]
It's well over time that we clean up our codebase. Android Studio can help us, but we should do it at a time with no open branches/pull requests so I guess it will be a good time soon.

I recommend that we use https://source.android.com/source/code-style.html as a base. I see the following tasks should be done:

- [x] Convert all tabbed indentation to spaces, re-indent everything
- [x] Re-order class members(?)
- [x] Put simple block expressions (``if`` without ``{…}``) on *one* line with their body
- [x] Enforce line length of 100 characters
- [x] Order all import statements
- [ ] Re-Think all our (empty or to generic) exception handlers
- [x] Ship a Android Studio style configuration with the project
- [x] Remove duplicate code by consolidating ``catch``-Statements
- [ ] Enforce this rules for the future using git hooks / a CI server / …
- [x] Remove german acronyms (e.g. "tvEntlHeader")
- [x] Make view IDs meaningful (avoid e.g. "textView1")
- [ ] Add more Javadocs
- [x] Get rid of ``Object...`` attributes (see comments below).
- [x] Reduce number of findViewById() calls by saving found Views in variables to improve performance and readability.

cc @johan12345

**Comment by johan12345** [comment]
More ideas:
[] Remove german acronyms (e.g. "tvEntlHeader")
[] Make view IDs meaningful (avoid e.g. "textView1")
[] Add more Javadocs (?)

**Comment by johan12345** [comment]
> Rename private fields (?)
Do you mean [This section](https://source.android.com/source/code-style.html#follow-field-naming-conventions), which suggests to name private fields starting with "m" and static fields with "s"? I didn't do that before and it's not in the ["official" naming conventions](http://www.oracle.com/technetwork/java/codeconventions-135099.html), but if you want to, we can set that in Android Studio's code style settings, too.
> Enforce this rules for the future using git hooks / a CI server / ...
Is there some software/service you have in mind? After a short search I didn't find anything like that compatible with Java.

Should we also use Java 7 features (compatible with Android since the [KitKat Build Tools](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Using-sourceCompatibility-1.7), but also with earlier versions) to simplify our code, for example by collapsing things like
```
try {
...
                } catch (java.net.SocketException e) {
                    exception = e;
                } catch (NoHttpResponseException e) {
                    exception = e;
                } catch (OpacErrorException e) {
                    exception = e;
                } catch (InterruptedIOException e) {
                    exception = e;
                }
```
(excerpt from SearchResultListFragment)
To a single `} catch (java.net.SocketException | NoHttpResponseException | OpacErrorException | InterruptedIOException) {` block ?

**Comment by raphaelm** [comment]
> Do you mean [This section](https://source.android.com/source/code-style.html#follow-field-naming-conventions), which suggests to name private fields starting with "m" and static fields with "s"? I didn't do that before and it's not in the ["official" naming conventions](http://www.oracle.com/technetwork/java/codeconventions-135099.html), but if you want to, we can set that in Android Studio's code style settings, too.

No. We'll stick to the Oracle conventions. I don't really like the "m" and "s" prefixes.

> Is there some software/service you have in mind? After a short search I didn't find anything like that compatible with Java.

Well, some day we'll want to have continous integration either way, so in the long run, we'll want a server building – and maybe testing – every commit or pull request in the repository. There are several options:
* Use Travis CI: nice and beautifully integrated into GitHub. Easiest option for the Open Source edition, but way to expensive for the Plus edition
* Host ourselves using Jenkins: Hardest option in terms of setup and maintenance
* Host ourselves using Bamboo: Also costs money, but less than Travis and integrates nicely with Jira

I'm still unsure what to choose here. Either way, in all of these would support running [Checkstyle](http://checkstyle.sourceforge.net/) or something similar. This would not reject commits which are violating the rules, but would send out warnings.
Additionally, a contributor can ``.git/hooks/pre-commit`` to do these checks locally before submitting any commit to the repository.

> Should we also use Java 7 features (compatible with Android since the [KitKat Build Tools](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Using-sourceCompatibility-1.7), but also with earlier versions) to simplify our code, for example by collapsing things like

If we can simplify something without breaking it, we sure do so :)

**Comment by johan12345** [comment]
Another idea:
[] Reduce number of `findViewById()` calls by saving found Views in variables to improve performance and readability.

**Comment by raphaelm** [comment]
> [ ] Reduce number of findViewById() calls by saving found Views in variables to improve performance and readability.

Sounds reasonable.

> [ ] Create custom classes for the arguments to avoid having to use AsyncTask<Object,...,...> (?)

Why? They don't share code (or do they?) so it would just add boilerplate Java files.

**Comment by johan12345** [comment]
> Why? They don't share code (or do they?) so it would just add boilerplate Java files.
I meant replacing a
```java
private class DoSomethingTask extends AsyncTask<Object, Void, Result>`
```
that needs many different arguments and casts them to their correct types inside `doInBackground()` with a
```java
private class DoSomethingTask extends AsyncTask<DoSomethingTask.ArgumentHolder, Void, Result>
```
to make sure we pass the correct arguments to the task. In the current implementation, we can only notice a wrong type or number of arguments at runtime, where it would throw a `ClassCastException`, for example. Another alternative would be to use the constructor for passing the arguments:
```java
private class DoSomethingTask extends AsyncTask<Void, Void, Result> {
    public DoSomethingTask(Type1 arg1, Type2 arg2, Type3 arg3) {
        ...
    }
}
```

**Comment by raphaelm** [comment]
Ah, that makes sense and sounds like a good idea.

**Comment by johan12345** [comment]
Would you rather use the first (Class for the arguments) or the second solution (constructor)? I think the second one probably produces less additional code.

**Comment by raphaelm** [comment]
Yes, I agree. I think we should go for the constructors.

**Comment by raphaelm** [comment]
I will transform ``except``-blocks now, just so we don't do the same thing ;)

**Comment by johan12345** [comment]
I already did that, just not pushed yet.

**Comment by raphaelm** [comment]
Okay :D

**Comment by johan12345** [comment]
I also went through many of the suggestions Android Studio made in the "code analysis" and created a pull request.

**Comment by raphaelm** [comment]
I did the same thing and pushed some more commits :)

**Comment by johan12345** [comment]
Okay :)
I'll change the AsyncTask argument implementations now, if you're not already doing that.

**Comment by raphaelm** [comment]
Go for it! :)

**Comment by hurzl** [comment]
remove android studio files like .idea and iml files from git?

**Comment by raphaelm** [comment]
Yes and No. It is generally encouraged to keep them there (see e.g. [here](http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project)) but it is a problem because of [this bug](https://code.google.com/p/android/issues/detail?id=156708&q=iml%20change&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars). We haven't yet decided whether we want to keep them or not.

**Comment by raphaelm** [comment]
I'll have this closed for now.
