### ISSUE TITLE
FH Bielefeld doesn't work

### ISSUE THREAD

**Issue by bodems** [raphaelm/opacclient#317]
Due to a server move, the domain for opac has been changed (I don't know why they changed the domain). The old domain biblio.fh-bielefeld.de resolves to 212.201.138.5 and doesn't work anymore, the new domain netbz05.fh-bielefeld.de resolves to 212.201.138.3. I think with https://netbz05.fh-bielefeld.de/webOPACClient in the json-file it should work again.

**Comment by raphaelm** [comment]
Thanks for the notification! :)
