### ISSUE TITLE
VOeBB: "Keine Suchfelder gefunden"

### ISSUE THREAD

**Issue by hurzl** [raphaelm/opacclient#320]
bei "Katalogsuche"

Wo muss ich den Fehler suchen?

**Comment by raphaelm** [comment]
https://github.com/raphaelm/opacclient/blob/master/opacclient/libopac/src/main/java/de/geeksfactory/opacclient/apis/Adis.java#L1367 ist die Funktion, die man jetzt debuggen muss :)

**Comment by hurzl** [comment]
... kaum debuggt man es, geht es wieder :/

**Comment by johan12345** [comment]
Dann war vielleicht einfach der VOeBB-Server kurzzeitig offline.

**Comment by hurzl** [comment]
Wäre dann natürlich besser, eine entsprechende Meldung zu bekommen

**Comment by johan12345** [comment]
Wenn der Server einfach gar nicht antwortet oder einen 404-Fehler zurückgibt, sollte auch die entsprechende Meldung ("Verbindung zum Bibliotheksserver konnte nicht hergestellt werden" oder so ähnlich) kommen, aber auf andere Fehlerseiten (die sich nicht per HTTP-Code zu erkennen geben) sind wir eben nicht vorbereitet. Falls es nochmal passiert, kannst du ja den HTML-Code von der Website speichern und schauen, ob dort irgendeine Fehlermeldung statt der Suchfelder ist.

**Comment by raphaelm** [comment]
Was @johan12345 sagt, wollte ich auch gerade schreiben ;) Ich halte das also für normalen Schluckauf, der kommt dank des furchtbaren Session-Systems von Adis nunmal in diesen Bibliotheken weiter vor. Wenn es öfter schiefgehen sollte, einfach wieder melden ;)
