### ISSUE TITLE
Tatsächlich ausleihen/bestellen

### ISSUE THREAD

**Issue by hurzl** [raphaelm/opacclient#325]
oder wenigstens Standorte/Verfügbarkeit abfragen, geht das schon irgendwo?

**Comment by raphaelm** [comment]
Ja, tatsächlich Vorbestellen geht, ebenso wie Verfügbarkeit abfragen, im absoluten Großteil der Bibliotheken. In Berlin nicht, weil Berlin an dieser Stelle das Bibliothekssystem mit einer Eigenentwicklung start abgeändert hat, d.h. man müsste eine ganze Menge Code nur für Berlin schreiben. Das darfst du gerne tun, wenn du Lust hast. Mein Tipp wäre, eine neue Api ``AdisVoebb`` zu erstellen, die ``Adis`` als Mutterklasse hat und nur die entsprechenden 2-3 Methoden erweitert.

**Comment by raphaelm** [comment]
Im Grund ist das genau der verbleibende offene Punkt von #214, daher mache ich das Ticket hier mal als doppelt zu ;)
