### ISSUE TITLE
Nur Titel in der Merkliste?

### ISSUE THREAD

**Issue by hurzl** [raphaelm/opacclient#326]
Es wird nur der Titel gemerkt? Beim Aufrufen des gemerkten wird die Suche neu gestartet und natürlich massenhaft Bücher gefunden, nur nicht das, was ich mir merken wollte ...

**Comment by johan12345** [comment]
Das geht bei manchen Bibliothekssystemen leider nicht anders, weil die Medien keine IDs haben, über die man sie finden kann.

**Comment by raphaelm** [comment]
Ja, in Bibliotheken, in denen ein Zugriff auf Medien ohne ID nicht möglich ist, weil das Bibliothekssystem uns das nicht bereitstellt, ist das so. Leider.

**Comment by hurzl** [comment]
Kann man sich nicht den Autor merken, dann wären die Ergebnisse meistens eindeutig?

**Comment by raphaelm** [comment]
Nein. Weil wir nicht wissen, was der Autor ist. Die Details zu einem Medium enthalten hundert Dinge, die in jeder Bibliothek anders heißen, mal heißen sie "Verfasser", mal "Autor", dann wieder "Regisseur" weils ne DVD ist usw.. Und selbst wenn das klappen würde, sind da noch die Biblitoheken in denen ein Verfasser bei der Suche als "Nachname, Vorname" eingegeben werden muss und in den Details andersrum dasteht. Oft heißt die Benennung der Zeile in den Details nicht mal genauso wie das Suchfeld – wir haben quasi keine Chance, das für mehrere hundert Bibliotheken sinnvoll zu bauen.

**Comment by hurzl** [comment]
Vielleicht wäre etwas wie "Suche eingrenzen" denkbar, generell für alle Suchergebnisse?
Und bei der Merkliste dann einfach das Suchformular mit dem Titel vor-ausfüllen?

**Comment by raphaelm** [comment]
Klar, das ist nen nettes Feature, das bieten wir derzeit den Bibliotheken an, die uns für die App bezahlen, damit wir ein paar verlockende Funktionen haben ;)

**Comment by hurzl** [comment]
:-1:
